### PR TITLE
Remove Info Icon from Desktop #411

### LINKED ISSUE #411: Remove Info Icon from Desktop
**Describe the bug**
An information icon appears in the bottom left corner of map on desktop.  Clicking on icon opens the tutorial modal.  This should not be there and should be removed. See screenshot below.

**To Reproduce**
open map on desktop

**Expected behavior**
n/a

**Screenshots**
image

**Desktop (please complete the following information):**
Windows 10

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by JosephAni**
# Pull Request

## Change Summary

Bug

## Change Reason

An information icon appears in the bottom left corner of map on desktop. Clicking on icon opens the tutorial modal. This should not be there and should be removed.

Related Issue: #<Github Issue Number (411)>

### CODE REVIEW

**Comment by JosephAni** [comment]
bug

File: src/components/ReactGoogleMaps/ReactGoogleMaps.js [hunk 1]
```diff
@@ -522,7 +522,7 @@ export class ReactGoogleMaps extends Component {
               search={location => this.searchForLocation(location)}
             />
             <TutorialModal
-              showButton={isMobile ? !this.state.isSearchBarShown : true}
+              showButton={isMobile ? !this.state.isSearchBarShown : false}
```
Comment (RNR1) [inline src/components/ReactGoogleMaps/ReactGoogleMaps.js:525]: nit: That might be more readable
```jsx
showButton={isMobile && !this.state.isSearchBarShown}
```

**Review by RNR1 — APPROVED** [review]
LGTM

**Comment by tomporvaz** [comment]
@RNR1 or @JosephAni Can you merge this one?
